blogproject/blog/urls.py
from django.conf.urls import url,include
from . import views
from blog.feeds import AllPostRssfeed

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    #url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.archives,name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^about$',views.about,name='about'),
    url(r'^contact$',views.contact,name='contact'),
    url(r'^articles/$',views.Articles.as_view(),name='articles'),
    url(r'^all/rss/$',AllPostRssfeed(),name='rss'),
    url(r'^search/$', views.search, name='search'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.TagView.as_view(),name='tag'),
]

# urlpatterns = [
#     url(r'^$',views.index,name='index'),
#     url(r'^article/(?P<pk>[0-9]+)/$',views.detail,name='detail'),
#     url(r'^archives/(?P<year>\d{4})/(?P<month>\d{1,2})/$',views.archives,name='archives'),
#     url(r'^category/(?P<pk>[0-9]+)/$',views.category,name='category'),
#     url(r'^articles/$',views.articles,name='articles'),
#     url(r'^about$',views.about,name='about'),
#     url(r'^contact$',views.contact,name='contact'),
#     url(r'^all/rss/$',AllPostRssfeed(),name='rss'),
#     url(r'^search/$', views.search, name='search'),
# ]

blogproject/blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'',include('comments.urls')),
]

blogproject/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/article/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
]

blogproject/blog/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
import markdown
from django.utils.html import strip_tags

class Category(models.Model):
    '''分类表'''
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Tag(models.Model):
    '''标签表'''
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class Post(models.Model):
    '''文章表'''
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateField()   #DateTimeField()
    modified_time = models.DateField()  #DateTimeField()
    excerpt = models.CharField(max_length=100,blank=True)
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag,blank=True)
    author = models.ForeignKey(User)
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-created_time']

class Message(models.Model):
    '''留言表'''
    name = models.CharField(max_length=20)
    user_email = models.EmailField()
    user_theme = models.CharField(max_length=100)
    user_text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user_email

blogproject/comments/models.py
from django.db import models

class Comment(models.Model):
    '''评论表'''
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=225)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    #关联文章
    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blogproject/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.shortcuts import render
from .models import Post,Tag,Category,Message
import markdown
from comments.forms import CommentForm
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView,DetailView
from django.db.models import Q
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.core.mail import send_mail
from time import strftime
from .m_forms import MessageForm


class IndexView(ListView):
    '''主页'''
    model = Post
    template_name = 'blog/index.html'
    context_object_name = "post_list"
    paginate_by = 5

class ArchivesView(ListView):
    '''归档分类'''
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 5

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month
                                                               )

class CategoryView(IndexView):
    '''标签分类'''
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)

class TagView(IndexView):
    '''标签'''
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)

def about(request):
    '''关于我的页面'''
    return render(request,'blog/about.html')

def contact(request):
    '''联系我的页面'''
    form = MessageForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            mlist = Message.objects.all().order_by('-create_time')
            mail_name = '留言人名称：'
            mail_content = '留言内容：'
            mail_email = '留言人邮件地址：'
            mail_text = mail_name + mlist[0].name + '\n' + mail_email + mlist[0].user_email + '\n' + mail_content + \
                        mlist[0].user_text
            send_mail(mlist[0].user_theme, mail_text, '3301885103@qq.com',
                      ['898829225@qq.com'], fail_silently=True)
        return redirect('/contact')
    else:
        return render(request, 'blog/contact.html',context={'form':form})
# def contact(request):
#     '''联系我的页面'''
#     if request.method == "GET":
#         return render(request, 'blog/contact.html')
#     elif request.method == "POST":
#         now = strftime('%Y-%m-%d %H:%M:%S')
#         mail_name = '留言人昵称：'
#         mail_content = '留言内容：'
#         mail_email = '留言人邮箱地址：'
#         texts = {}
#         texts['name'] = request.POST['name']
#         texts['user_email'] = request.POST['email']
#         texts['user_theme'] = request.POST['subject']
#         texts['user_text'] = request.POST['message']
#         Message.objects.create(name=texts['name'],user_email=texts['user_email'],user_theme=texts['user_theme'],user_text=texts['user_text'],message_time=now)
#         mail_text = mail_name + texts['name'] + '\n\n' + mail_email + texts['user_email'] + '\n\n' + mail_content + texts['user_text']

#         send_mail(texts['user_theme'], mail_text, '3301885103@qq.com',
#                       ['898829225@qq.com'], fail_silently=True)
#         return render(request, 'blog/contact.html')

class Articles(IndexView):
    '''博客页面'''
    model = Post
    template_name = 'blog/articles.html'
    context_object_name = 'post_list'
    paginate_by = 5

def search(request):
    '''搜索页面'''
    q = request.GET.get('q')
    error_msg = ''
    if not q:
        error_msg = '请输入关键词'
        return render(request,'blog/index.html',{'error_msg':error_msg})
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request,'blog/index.html',{'error_msg':error_msg,'post_list':post_list})

class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(post.body,
                                      extensions=[
                                          'markdown.extensions.extra',
                                          'markdown.extensions.codehilite',
                                          #'markdown.extensions.toc',
                                          TocExtension(slugify=slugify),
                                      ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外（DetailView 已经帮我们完成），
        # 还要把评论表单、post 下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context

# def category(request,pk):
#     '''分类'''
#     cate = get_object_or_404(Category,pk=pk)
#     post_list = Post.objects.filter(category=cate)#.order_by('-created_time')
#     return render(request,'blog/index.html',context={'post_list':post_list})

# def articles(request):
#     '''博客页面'''
#     post_list = Post.objects.all()#.order_by('-created_time')
#     return render(request,'blog/articles.html',context={'post_list':post_list})

# def archives(request,year,month):
#     '''归档分类'''
#     post_list = Post.objects.filter(created_time__year=year,created_time__month=month)
#     print(post_list)
#     return render(request,'blog/index.html',context={"post_list":post_list})

# def detail(request,pk):
#     '''文章详情页'''
#     post = get_object_or_404(Post, pk=pk)
#     post.increase_views
#     post.body = markdown.markdown(post.body,
#                                      extensions=[
#                                          'markdown.extensions.extra',
#                                          'markdown.extensions.codehilite',
#                                          'markdown.extensions.toc',
#                                      ]
#                                      )
#     form = CommentForm()
#     comment_list = post.comment_set.all()
#     context = {'post':post,
#                'form':form,
#                'comment_list':comment_list}
#
#     return render(request, 'blog/detail.html',context=context)

# def index(request):
#     '''主页'''
#     post_list = Post.objects.all()#.order_by('-created_time')
#     return render(request,'blog/index.html',context={'post_list':post_list})

blogproject/templates/blog/about.html
{% extends "base_2.html" %}

{% load staticfiles %}
{% block main %}
<div class="content-body">
<div class="container">
    <div class="row">
        <main class="col-md-12">
            <h1 class="page-title">关于我</h1>
            <article class="post">
                <div class="entry-content clearfix">
                    <figure class="img-responsive-center">
                        <img class="img-responsive" src="{% static 'blog/img/me.jpg' %}" alt="Developer Image">
                    </figure>
                    <p>喜欢探讨，各种技术，但自己却是个菜鸟。目前在学习Python Django相关知识。希望能成为一名及格的程序员。✌️</p>
                    <p>虽然我一直一厢情愿的认为自己是名程序员，但是理想不能放弃！！！</p>
                    <div class="height-40px"></div>
                    <h2 class="title text-center">社交</h2>
                    <ul class="social">
                        <li class="facebook"><a href="http://www.jianshu.com/nb/11058152"><span class="ion-social-facebook"></span></a></li>
                        <li class="twitter"><a href="http://www.jianshu.com/nb/11058152"><span class="ion-social-twitter"></span></a></li>
                        <li class="google-plus"><a href="http://www.jianshu.com/nb/11058152"><span class="ion-social-googleplus"></span></a></li>
                        <li class="tumblr"><a href="https://github.com/YGQ8988"><span class="ion-social-tumblr"></span></a></li>
                    </ul>
                </div>
            </article>
        </main>
    </div>
</div>
</div>
{% endblock main %}

blogproject/templates/blog/articles.html
{% extends 'base_2.html' %}

{% block main %}
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
            {% for post in post_list %}
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></span>

                            <span class="post-date"><a><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>

                            <span class="post-author"><a href="{% url 'blog:about' %}">{{ post.author }}</a></span>

                            <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>

                            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{ post.excerpt }}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
            {% empty %}
                暂无文章！
            {% endfor %}
        {% if is_paginated %}
        <div class="pagination-simple">
            <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        <!-- 显示当前页面信息 -->
        <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
        <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
        </div>
        {% endif %}
            </main>
        </div>
    </div>
</div>
{% endblock %}

blogproject/templates/blog/contact.html
{% extends "base_2.html" %}

{% block main %}
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                <h1 class="page-title">联系方式</h1>
                <article class="post">
                    <div class="entry-content clearfix">
                        <form action="{% url 'blog:contact' %}" method="post" class="contact-form">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 col-md-offset-3">
                                    <p>昵称</p>
                                    {{ form.name }}
                                    <p>邮箱地址</p>
                                    {{ form.user_email }}
                                    <p>主题</p>
                                    {{ form.user_theme }}
                                    <p>您想说的</p>
                                    {{ form.user_text }}
                                    <!-- <input type="text" name="name" placeholder="名字" required>
                                    <input type="email" name="email" placeholder="邮箱地址" required>
                                    <input type="text" name="subject" placeholder="主题" required>
                                    <textarea name="message" rows="7" placeholder="您想说的" required></textarea> -->
                                    <button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>发送给我</span></button>
                                </div>
                            </div>	<!-- row -->
                        </form>
                    </div>
                </article>
            </main>
        </div>
    </div>
</div>
{% endblock %}

blogproject/templates/blog/detail.html
{% extends "base.html" %}

{% block main %}
    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url "blog:category" post.category.pk %}">{{ post.category }}</a></span>
                <span class="post-date"><a><time class="entry-date"
                                                          datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="{% url 'blog:about' %}">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
            </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{ comment.name }}</span>
                    <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment.created_time }}</time>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </li>
            {% empty %}
                暂无评论！
            {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}

{% block toc %}
     <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>
{% endblock toc %}

blogproject/templates/blog/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block main %}
    {% if post_list == None %}
        <p>搜索无结果</p>
    {% endif %}

    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="{% url "blog:category" post.category.pk %}">{{ post.category.name }}</a></span>
                    <span class="post-date"><a><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="{% url 'blog:about' %}">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                        </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    <!-- 简单分页效果
            <div class="pagination-simple">
                <a href="#">上一页</a>
                <span class="current">第 6 页 / 共 11 页</span>
                <a href="#">下一页</a>
            </div>
            -->
{#    <div class="pagination">#}
{#        <ul>#}
{#            <li><a href="">1</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">4</a></li>#}
{#            <li><a href="">5</a></li>#}
{#            <li class="current"><a href="">6</a></li>#}
{#            <li><a href="">7</a></li>#}
{#            <li><a href="">8</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">11</a></li>#}
{#        </ul>#}
{#    </div>#}
{% if is_paginated %}
<div class="pagination-simple">
  <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
  {% endif %}
  <!-- 显示当前页面信息 -->
  <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
  <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
  {% endif %}
</div>
{% endif %}
{% endblock main %}